### ISSUE TITLE
สร้างโปรเจคขึ้นมาให้สามารถทำงานได้

### ISSUE THREAD

**Issue by pchaow** [SEUP/SEMock1#1]
1. สร้าง android app project ด้วยภาษา kotlin เพื่อให้สามารถรันได้

**Comment by pchaow** [comment]
ฝาก อ.เป้ ช่วยดูแลปัญหานี้ด้วย

**Comment by chontipan** [comment]
แก้ไขปัญหาเรียบร้อยครับ
